#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-0 --auto --primary --output DP-0 --auto --right-of HDMI-0

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap -layout us,ru -option grp:caps_toggle
setxkbmap -option caps:none
~/.config/polybar/grayblocks/launch.sh &
~/.config/polybar/colorblocks/launch.sh &
feh --no-fehbg --bg-fill ~/Images/1113344.jpg ~/Images/1Mon.png
